### PR TITLE
Feature/issue 345

### LINKED ISSUE #345: Joining to a table that has no non-key fields raises 'AssertionError: indices is empty'
Urgency: LOW
Error Message: "AssertionError: indices is empty"
Code Snippet:
Suggestion: Joins between tables that contain only key columns should work.

```python
# petl v1.0.11
import petl as etl

c = [['id','val'],[20,1],[3,1],[6,1],[12,1],[15,1]]
u = [['id','val'],[3,2],[6,2],[9,2],[12,2],[15,2]]
etl.join(c,u,key='id')

+----+-----+-----+
| id | val | val |
+====+=====+=====+
|  3 |   1 |   2 |
+----+-----+-----+
|  6 |   1 |   2 |
+----+-----+-----+
| 12 |   1 |   2 |
+----+-----+-----+
| 15 |   1 |   2 |
+----+-----+-----+

u = etl.cut(u,'id')
etl.join(c,u,key='id')

...

/tank/etl/anaconda3/lib/python3.4/site-packages/petl/util/base.py in
rowgetter(*indices)
    308
    309     # guard condition
--> 310     assert len(indices) > 0, 'indices is empty'
    311
    312     # if only one index, we cannot use itemgetter, because we
want a singleton

AssertionError: indices is empty
```

### PR DESCRIPTION
**Pull request by rogerkwoodley**
Resolves #345, added test cases.

For joins, fields in a table fall into two classes: keys and values.
Existing join implementations retrieved all value fields from the row, then merged it with the other table.
In cases where a table contains ONLY keys, the rowgetter() function fails as there are no fields to retrieve.

To work around this, we now test if there are any value rows.  Then we rely on a helper "extend_row()" function, which either extends the row if there are new value fields, or returns the row as is if there are no value rows.

iterhashrightjoin() allowed for a unique situation, wherein the left table contains only keys.  The existing implementation simply created a list out of the rows, then appended the right values to it.  Since there now exist cases where the left table contains only integers, the call to list() fails.  Strings also present an issue, as you can create a list('abc') which yields ['a', 'b', 'c'].  This is guarded against with clean_list(), which cleanly generates a list to satisfy known cases (existing cases, int/floats, strings).

Another item came up during testing - the nosetests fail if the sort order of the tables are different (which is common with the hash joins).  It's easy to recreate by simply changing the keys to strings (e.g., 'one', 'two', etc.)

This affects all of the tests.  I'll open a ticket to extend the nose test helpers to include some test similar to assertItemsEqual() (Py 2.x) or assertCountEqual() (Py 3.2+)

### CODE REVIEW

**Comment by alimanfoo** [comment]
Aaa, looks like we were working on the same issue at the same time! Great minds...

I just pushed some changes to master then saw your PR. I will take a careful look at what you have here and figure out how best to merge. Thanks for taking the time to work on this, I think you've thought of some cases I've missed. In any case I'll drop a note on any issue I start working on from now on so we can avoid any duplication.

**Comment by rogerkwoodley** [comment]
Sorry about that - I'll post a note next time :smile:

**Comment by alimanfoo** [comment]
No worries at all, it is wonderful to have another pair of eyes on this! In fact it looks like great minds after all, as we have both come up with what is effectively the exact same solution to the problem :-) The only real difference is that instead of the clean_list() function, I think there was actually a bug in the behaviour of lookup() when given a table with only one column. I modified lookup() to return a row (tuple) instead of a value, and that this removes the need for the clean_list() check.

**Comment by alimanfoo** [comment]
This fix is effectively merged so closing.

**Comment by alimanfoo** [comment]
@rogerkwoodley regarding the sort order problem, please do open an issue for that.

**Comment by rogerkwoodley** [comment]
Opened #353 for sort order tests

**Pull request closed without merging**
